//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class HotSpotDB
    {
        public int SNO { get; set; }
        public string id { get; set; }
        public string spot_name { get; set; }
        public string type { get; set; }
        public string company { get; set; }
        public string district { get; set; }
        public string address { get; set; }
        public string apparatus_name { get; set; }
        public string latitude { get; set; }
        public string longitude { get; set; }
    }
}
