//------------------------------------------------------------------------------
// <auto-generated>
//     這個程式碼是由範本產生。
//
//     對這個檔案進行手動變更可能導致您的應用程式產生未預期的行為。
//     如果重新產生程式碼，將會覆寫對這個檔案的手動變更。
// </auto-generated>
//------------------------------------------------------------------------------

namespace DataApi.Models
{
    using System;
    using System.Collections.Generic;
    
    public partial class RealData
    {
        public int id { get; set; }
        public string store_id { get; set; }
        public string data_generated_dtime { get; set; }
        public string data_start_dtime { get; set; }
        public string data_end_dtime { get; set; }
        public string item_id { get; set; }
        public string item_external_id { get; set; }
        public string item_setting_external_id { get; set; }
        public string item_name { get; set; }
        public string item_category_id { get; set; }
        public string item_category_name { get; set; }
        public Nullable<decimal> quantity { get; set; }
    }
}
